all: confirmfmv.jar

confirmfmv.jar:
	rm -f $@
	find . -type f -not -name "Makefile.chrome" | cut -c3- | xargs jar -Mcf $@

babelzilla:
	rm -f confirmfmv.jar
	find . -type f -not -name "Makefile.chrome" | cut -c3- | xargs jar -Mcf confirmfmv.jar
