all: confirmfmv.jar

confirmfmv.jar:
	rm -f $@
	find . -type f -not -name "Makefile.chrome" -and -not -name "install.properties" -and -not -path "*.svn*" | cut -c3- |xargs jar -Mcf $@

babelzilla:
	rm -f confirmfmv.jar
	find . -type f -not -name "Makefile.chrome" -and -not -path "*.svn*" | cut -c3- |xargs jar -Mcf confirmfmv.jar
